name: area_mobile
description: "AREA mobile application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  http: ^1.2.0
  
  flutter_secure_storage: ^9.0.0
  
  app_links: ^6.0.2
  url_launcher: ^6.2.4
  
  flutter_dotenv: ^5.1.0
  
  provider: ^6.1.1
  
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/logo.png

flutter_launcher_icons:
  image_path: assets/logo.png
  android: true
  ios: true
  adaptive_icon_background: "#FFFFFF"
  remove_alpha_ios: true
